### PR TITLE
updated fabric8 maven plugin

### LINKED ISSUE #25: update fabric8 maven plugin for OSIO boosters
In the context of [openshift.io application deployment](https://github.com/openshiftio/openshift.io/issues/2505#issuecomment-371732158) an important [issue (#1226)](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/CHANGELOG.md) has been fixed in the recent release of fabric8 maven plugin (FMP).
Need to update FMP dependency to v3.5.38  for openshift.io boosters accordingly.

### PR DESCRIPTION
**Pull request by hrishin**
- updated fabric8 maven plugin to v.3.5.38

Fix #25

### CODE REVIEW

**Comment by hrishin** [comment]
@cescoffier could you review it?
Please let me know how can get it updated in respective boosters applciations

**Comment by kenfinnigan** [comment]
I believe it wouldn't be possible for WF Swarm boosters to update to a parent version that included this fix without https://github.com/fabric8io/fabric8-maven-plugin/pull/1216 being present.

@Ladicek would be able to confirm

**Comment by cescoffier** [comment]
@kenfinnigan absolutely, and this is actually a blocker for Vert.x too.

**Comment by Ladicek** [comment]
The booster parent sets the `fabric8.generator.from` property to the Red Hat OpenJDK S2I image, thereby completely avoiding the issue @kenfinnigan mentions. That issue is caused by FMP automatically selecting a new version of the Fabric8 Java S2I image. Actually that's been happening since FMP 3.5.34, and the latest booster-parent already sets FMP to 3.5.35.

**Comment by cescoffier** [comment]
Thanks @Ladicek, so we can go ahead and release the parent ?

**Comment by Ladicek** [comment]
I believe this is safe to merge, yes.

(I think we could also delete the `fabric8.skip.build.pom` property, as FMP 3.5.38 reverts that breaking change, but it's probably more future-proof to keep it, as FMP plans to re-introduce that change later.)

**Comment by cescoffier** [comment]
Merged, thanks! 

I will release the booster parent later Today.

**Comment by cescoffier** [comment]
Release in progress....

**Pull request merged**
