### PR TITLE
chore: version bump arquillian-cube to 1.15.2

### PR DESCRIPTION
**Pull request by hemanik**
Updates arquillian-cube to latest version.

### CODE REVIEW

**Comment by hemanik** [comment]
@cescoffier, when can we have the new booster-parent release with this change?  

We have a bunch of improvements around Cube with the new version which we would like to contribute to boosters.

**Comment by cescoffier** [comment]
@hemanik cool! Yes, I will cut a new release Today. Will let you know when it reaches Maven Central.

**Comment by cescoffier** [comment]
@hemanik release is in maven central!

**Comment by hemanik** [comment]
Thank you @cescoffier

**Pull request merged**
